# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: pichrist <pichrist@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2016/08/19 09:41:20 by hmahtout          #+#    #+#              #
#    Updated: 2016/08/20 22:54:04 by pichrist         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = src/*.c
HEADERS = includes/*.h
NAME = a.out

all :
	gcc $(SRC) -I $(HEADERS) -o $(NAME)

clean :
	rm -f colle-2

re : clean all
